codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 3%
        if_ci_failed: error
    changes:
      default:
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/__tests__/**"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/jest.setup.ts"

flags:
  unit:
    paths:
      - src/
    carryforward: true
